# fly.toml - Pong Server
app = 'ems-pong'
primary_region = 'ord'

[build]
  dockerfile = 'apps/pong-server/Dockerfile'
  build-target = 'runner'
  [build.args]

[env]
  NODE_ENV = 'production'
  PONG_SERVER_PORT = '5001'

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[http_service.checks]]
  grace_period = '10s'
  interval = '30s'
  method = 'GET'
  timeout = '5s'
  path = '/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpus = 1
