// Full Achievement Catalog for elonmusksucks.net
// Maps to comprehensive badge list with proper categorization and rarity

interface AchievementSeed {
  slug: string;
  name: string;
  title: string;
  description: string;
  category: string;
  rarity: 'common' | 'uncommon' | 'rare' | 'legendary' | 'secret' | 'shame';
  targetValue: number;
  autoAward: boolean;
  manualOnly: boolean;
  isShame: boolean;
  iconUrl?: string;
  sortOrder: number;
}

const SEED_ACHIEVEMENTS: AchievementSeed[] = [
  // === BETTING & PARLAY CATEGORY ===
  {
    slug: 'muskbucks-millionaire',
    name: 'MuskBucks Millionaire',
    title: 'MuskBucks Millionaire',
    description: 'Earn ≥1,000,000 MuskBucks net profit from betting',
    category: 'betting',
    rarity: 'legendary',
    targetValue: 1000000,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 100,
  },
  {
    slug: 'big-spender',
    name: 'Big Spender',
    title: 'Big Spender',
    description: 'Place a single bet with stake ≥100,000 MuskBucks',
    category: 'betting',
    rarity: 'rare',
    targetValue: 100000,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 101,
  },
  {
    slug: 'yolo-all-in',
    name: 'YOLO All-In',
    title: 'YOLO All-In',
    description: 'Go all-in with your entire balance and win',
    category: 'betting',
    rarity: 'rare',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 102,
  },
  {
    slug: 'paper-hands',
    name: 'Paper Hands',
    title: 'Paper Hands',
    description: 'Lose 5 bets in a row',
    category: 'betting',
    rarity: 'common',
    targetValue: 5,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 103,
  },
  {
    slug: 'diamond-hands',
    name: 'Diamond Hands',
    title: 'Diamond Hands',
    description: 'Win 10 bets in a row',
    category: 'betting',
    rarity: 'rare',
    targetValue: 10,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 104,
  },
  {
    slug: 'parlay-prodigy',
    name: 'Parlay Prodigy',
    title: 'Parlay Prodigy',
    description: 'Win a parlay with 3 or more legs',
    category: 'betting',
    rarity: 'uncommon',
    targetValue: 3,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 105,
  },
  {
    slug: 'the-long-shot',
    name: 'The Long Shot',
    title: 'The Long Shot',
    description: 'Win a bet with implied odds less than 10%',
    category: 'betting',
    rarity: 'rare',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 106,
  },
  {
    slug: 'bankrupt-billionaire',
    name: 'Bankrupt Billionaire',
    title: 'Bankrupt Billionaire',
    description: 'Your MuskBucks balance hits zero',
    category: 'betting',
    rarity: 'uncommon',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 107,
  },
  {
    slug: 'rags-to-riches',
    name: 'Rags to Riches',
    title: 'Rags to Riches',
    description: 'Go from <100 to ≥50,000 MuskBucks in the same day',
    category: 'betting',
    rarity: 'rare',
    targetValue: 50000,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 108,
  },
  
  // === LEADERBOARD CATEGORY ===
  {
    slug: 'high-roller',
    name: 'High Roller',
    title: 'High Roller',
    description: 'Hold #1 position on leaderboard for 7 consecutive days',
    category: 'leaderboard',
    rarity: 'legendary',
    targetValue: 7,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 200,
  },
  {
    slug: 'chief-musk-whisperer',
    name: 'Chief Musk Whisperer',
    title: 'Chief Musk Whisperer',
    description: 'Finish #1 on the weekly leaderboard',
    category: 'leaderboard',
    rarity: 'rare',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 201,
  },
  {
    slug: 'rocket-fumbler',
    name: 'Rocket Fumbler',
    title: 'Rocket Fumbler',
    description: 'Finish last place on weekly leaderboard (among active bettors)',
    category: 'leaderboard',
    rarity: 'uncommon',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 202,
  },
  {
    slug: 'whale-of-wall-street',
    name: 'Whale of Wall Street',
    title: 'Whale of Wall Street',
    description: 'Have the largest single-day profit site-wide',
    category: 'leaderboard',
    rarity: 'rare',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 203,
  },
  {
    slug: 'clown-of-the-week',
    name: 'Clown of the Week',
    title: 'Clown of the Week',
    description: 'Place the single biggest losing bet of the week',
    category: 'leaderboard',
    rarity: 'uncommon',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 204,
  },

  // === PREDICTION CREATION CATEGORY ===
  {
    slug: 'prophet-of-mars',
    name: 'Prophet of Mars',
    title: 'Prophet of Mars',
    description: 'Create a prediction that receives over 100 bets',
    category: 'prediction',
    rarity: 'rare',
    targetValue: 100,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 300,
  },
  {
    slug: 'chaos-agent',
    name: 'Chaos Agent',
    title: 'Chaos Agent',
    description: 'Have 10 predictions approved by admins',
    category: 'prediction',
    rarity: 'uncommon',
    targetValue: 10,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 301,
  },
  {
    slug: 'trendsetter',
    name: 'Trendsetter',
    title: 'Trendsetter',
    description: 'First to create prediction about an event that actually happens',
    category: 'prediction',
    rarity: 'legendary',
    targetValue: 1,
    autoAward: false,
    manualOnly: true,
    isShame: false,
    sortOrder: 302,
  },
  {
    slug: 'cursed-predictor',
    name: 'Cursed Predictor',
    title: 'Cursed Predictor',
    description: 'Five of your created predictions resolve in unexpected ways',
    category: 'prediction',
    rarity: 'uncommon',
    targetValue: 5,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 303,
  },
  {
    slug: 'musk-whisperer',
    name: 'Musk Whisperer',
    title: 'Musk Whisperer',
    description: 'Create prediction about Elon that resolves correctly within 24h',
    category: 'prediction',
    rarity: 'rare',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 304,
  },

  // === CHAT & SOCIAL CATEGORY ===
  {
    slug: 'keyboard-warrior',
    name: 'Keyboard Warrior',
    title: 'Keyboard Warrior',
    description: 'Send 1,000 messages in global chat',
    category: 'chat',
    rarity: 'uncommon',
    targetValue: 1000,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 400,
  },
  {
    slug: 'chief-shitposter',
    name: 'Chief Shitposter',
    title: 'Chief Shitposter',
    description: 'Get 50+ upvotes on a single profile post',
    category: 'chat',
    rarity: 'rare',
    targetValue: 50,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 401,
  },
  {
    slug: 'reply-guy',
    name: 'Reply Guy',
    title: 'Reply Guy',
    description: 'Comment on 50 different user profile posts',
    category: 'chat',
    rarity: 'uncommon',
    targetValue: 50,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 402,
  },
  {
    slug: 'community-meme-lord',
    name: 'Community Meme Lord',
    title: 'Community Meme Lord',
    description: 'Post a meme that gets 100+ upvotes',
    category: 'chat',
    rarity: 'rare',
    targetValue: 100,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 403,
  },
  {
    slug: 'elon-reply-intern',
    name: 'Elon Reply Intern',
    title: 'Elon Reply Intern',
    description: 'Be the first to reply to an AI Elon tweet',
    category: 'chat',
    rarity: 'uncommon',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 404,
  },
  {
    slug: 'free-speech-absolutist',
    name: 'Free Speech Absolutist',
    title: 'Free Speech Absolutist',
    description: 'Participate in a chat thread with 100+ messages',
    category: 'chat',
    rarity: 'uncommon',
    targetValue: 100,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 405,
  },

  // === PARTICIPATION & STATS CATEGORY ===
  {
    slug: 'consistent-gambler',
    name: 'Consistent Gambler',
    title: 'Consistent Gambler',
    description: 'Place at least one bet every day for 30 days straight',
    category: 'participation',
    rarity: 'rare',
    targetValue: 30,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 500,
  },
  {
    slug: 'late-stage-capitalist',
    name: 'Late Stage Capitalist',
    title: 'Late Stage Capitalist',
    description: 'Earn 5,000,000 lifetime MuskBucks through betting',
    category: 'participation',
    rarity: 'legendary',
    targetValue: 5000000,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 501,
  },
  {
    slug: 'early-adopter',
    name: 'Early Adopter',
    title: 'Early Adopter',
    description: 'Joined within the first 30 days of launch',
    category: 'participation',
    rarity: 'rare',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 502,
  },
  {
    slug: 'conspiracy-theorist',
    name: 'Conspiracy Theorist',
    title: 'Conspiracy Theorist',
    description: 'Participate in 50+ different predictions',
    category: 'participation',
    rarity: 'uncommon',
    targetValue: 50,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 503,
  },
  {
    slug: 'ultimate-degenerate',
    name: 'Ultimate Degenerate',
    title: 'Ultimate Degenerate',
    description: 'Place 500+ bets in your lifetime',
    category: 'participation',
    rarity: 'rare',
    targetValue: 500,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 504,
  },
  {
    slug: 'bug-hunter',
    name: 'Bug Hunter',
    title: 'Bug Hunter',
    description: 'Report a bug that gets fixed by the development team',
    category: 'participation',
    rarity: 'uncommon',
    targetValue: 1,
    autoAward: false,
    manualOnly: true,
    isShame: false,
    sortOrder: 505,
  },

  // === EVENT-BASED CATEGORY ===
  {
    slug: 'dogefather-believer',
    name: 'Dogefather Believer',
    title: 'Dogefather Believer',
    description: 'Correctly predict when Elon tweets about Dogecoin',
    category: 'event',
    rarity: 'rare',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 600,
  },
  {
    slug: 'mars-colony-ceo',
    name: 'Mars Colony CEO',
    title: 'Mars Colony CEO',
    description: 'Correctly predict a SpaceX Mars mission announcement',
    category: 'event',
    rarity: 'legendary',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 601,
  },
  {
    slug: 'tesla-stonk-hodler',
    name: 'Tesla Stonk Hodler',
    title: 'Tesla Stonk Hodler',
    description: 'Correctly predict a major TSLA stock price movement',
    category: 'event',
    rarity: 'rare',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 602,
  },
  {
    slug: 'xtreme-x-user',
    name: 'Xtreme X User',
    title: 'Xtreme X User',
    description: 'Win 10 predictions in a row about Twitter/X changes',
    category: 'event',
    rarity: 'rare',
    targetValue: 10,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 603,
  },

  // === SECRET CATEGORY (Manual Awards Only) ===
  {
    slug: 'cult-leader',
    name: 'Cult Leader',
    title: 'Cult Leader',
    description: 'Build an impressive following through charismatic predictions',
    category: 'secret',
    rarity: 'secret',
    targetValue: 1,
    autoAward: false,
    manualOnly: true,
    isShame: false,
    sortOrder: 700,
  },
  {
    slug: 'banhammer-survivor',
    name: 'Banhammer Survivor',
    title: 'Banhammer Survivor',
    description: 'Return from a temporary ban stronger than ever',
    category: 'secret',
    rarity: 'secret',
    targetValue: 1,
    autoAward: false,
    manualOnly: true,
    isShame: false,
    sortOrder: 701,
  },
  {
    slug: 'true-visionary',
    name: 'True Visionary',
    title: 'True Visionary',
    description: 'Demonstrate exceptional foresight in multiple predictions',
    category: 'secret',
    rarity: 'secret',
    targetValue: 1,
    autoAward: false,
    manualOnly: true,
    isShame: false,
    sortOrder: 702,
  },
  {
    slug: 'rocket-man',
    name: 'Rocket Man',
    title: 'Rocket Man',
    description: 'Show deep understanding of SpaceX and space technology',
    category: 'secret',
    rarity: 'secret',
    targetValue: 1,
    autoAward: false,
    manualOnly: true,
    isShame: false,
    sortOrder: 703,
  },
  {
    slug: 'dumpster-fire-aficionado',
    name: 'Dumpster Fire Aficionado',
    title: 'Dumpster Fire Aficionado',
    description: 'Master of predicting spectacular corporate failures',
    category: 'secret',
    rarity: 'secret',
    targetValue: 1,
    autoAward: false,
    manualOnly: true,
    isShame: false,
    sortOrder: 704,
  },

  // === SHAME WALL CATEGORY (Banned Users) ===
  {
    slug: 'perma-banned-legend',
    name: 'Perma-banned Legend',
    title: 'Perma-banned Legend',
    description: 'Received a permanent ban from the platform',
    category: 'shame',
    rarity: 'shame',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: true,
    sortOrder: 800,
  },
  {
    slug: 'one-week-timeout',
    name: 'One Week Timeout',
    title: 'One Week Timeout',
    description: 'Served a 7-day temporary ban',
    category: 'shame',
    rarity: 'shame',
    targetValue: 7,
    autoAward: true,
    manualOnly: false,
    isShame: true,
    sortOrder: 801,
  },
  {
    slug: 'community-menace',
    name: 'Community Menace',
    title: 'Community Menace',
    description: 'Banned 3 or more times for disruptive behavior',
    category: 'shame',
    rarity: 'shame',
    targetValue: 3,
    autoAward: true,
    manualOnly: false,
    isShame: true,
    sortOrder: 802,
  },
  {
    slug: 'scammer-of-muskbucks',
    name: 'Scammer of MuskBucks',
    title: 'Scammer of MuskBucks',
    description: 'Attempted to exploit the MuskBucks system',
    category: 'shame',
    rarity: 'shame',
    targetValue: 1,
    autoAward: false,
    manualOnly: true,
    isShame: true,
    sortOrder: 803,
  },

  // === ADDITIONAL BETTING ACHIEVEMENTS ===
  {
    slug: 'first-timer',
    name: 'First Timer',
    title: 'First Timer',
    description: 'Place your very first bet',
    category: 'betting',
    rarity: 'common',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 109,
  },
  {
    slug: 'betting-machine',
    name: 'Betting Machine',
    title: 'Betting Machine',
    description: 'Place 100 total bets',
    category: 'betting',
    rarity: 'uncommon',
    targetValue: 100,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 110,
  },
  {
    slug: 'whale-bettor',
    name: 'Whale Bettor',
    title: 'Whale Bettor',
    description: 'Place a bet worth 500,000+ MuskBucks',
    category: 'betting',
    rarity: 'legendary',
    targetValue: 500000,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 111,
  },
  {
    slug: 'comeback-king',
    name: 'Comeback King',
    title: 'Comeback King',
    description: 'Win after being down 90% of your bankroll',
    category: 'betting',
    rarity: 'rare',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 112,
  },
  {
    slug: 'diversified-gambler',
    name: 'Diversified Gambler',
    title: 'Diversified Gambler',
    description: 'Place bets in 10 different prediction categories',
    category: 'betting',
    rarity: 'uncommon',
    targetValue: 10,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 113,
  },
  {
    slug: 'speed-demon',
    name: 'Speed Demon',
    title: 'Speed Demon',
    description: 'Place 10 bets in under 5 minutes',
    category: 'betting',
    rarity: 'uncommon',
    targetValue: 10,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 114,
  },
  {
    slug: 'parlay-master',
    name: 'Parlay Master',
    title: 'Parlay Master',
    description: 'Win a 5+ leg parlay',
    category: 'betting',
    rarity: 'legendary',
    targetValue: 5,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 115,
  },
  {
    slug: 'lucky-seven',
    name: 'Lucky Seven',
    title: 'Lucky Seven',
    description: 'Win 7 bets in a row',
    category: 'betting',
    rarity: 'uncommon',
    targetValue: 7,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 116,
  },

  // === ADDITIONAL LEADERBOARD ACHIEVEMENTS ===
  {
    slug: 'weekend-warrior',
    name: 'Weekend Warrior',
    title: 'Weekend Warrior',
    description: 'Finish in top 3 on weekend leaderboard',
    category: 'leaderboard',
    rarity: 'uncommon',
    targetValue: 3,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 205,
  },
  {
    slug: 'monthly-champion',
    name: 'Monthly Champion',
    title: 'Monthly Champion',
    description: 'Finish #1 on monthly leaderboard',
    category: 'leaderboard',
    rarity: 'legendary',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 206,
  },
  {
    slug: 'comeback-artist',
    name: 'Comeback Artist',
    title: 'Comeback Artist',
    description: 'Rise from bottom 10% to top 10% in a week',
    category: 'leaderboard',
    rarity: 'rare',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 207,
  },
  {
    slug: 'consistency-king',
    name: 'Consistency King',
    title: 'Consistency King',
    description: 'Stay in top 10 for 30 consecutive days',
    category: 'leaderboard',
    rarity: 'legendary',
    targetValue: 30,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 208,
  },

  // === ADDITIONAL PREDICTION ACHIEVEMENTS ===
  {
    slug: 'prediction-pioneer',
    name: 'Prediction Pioneer',
    title: 'Prediction Pioneer',
    description: 'Create your first prediction',
    category: 'prediction',
    rarity: 'common',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 305,
  },
  {
    slug: 'prediction-factory',
    name: 'Prediction Factory',
    title: 'Prediction Factory',
    description: 'Create 50 predictions',
    category: 'prediction',
    rarity: 'rare',
    targetValue: 50,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 306,
  },
  {
    slug: 'viral-predictor',
    name: 'Viral Predictor',
    title: 'Viral Predictor',
    description: 'Create a prediction with 500+ bets',
    category: 'prediction',
    rarity: 'legendary',
    targetValue: 500,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 307,
  },
  {
    slug: 'crystal-ball',
    name: 'Crystal Ball',
    title: 'Crystal Ball',
    description: 'Have 80%+ accuracy on your created predictions',
    category: 'prediction',
    rarity: 'legendary',
    targetValue: 80,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 308,
  },

  // === ADDITIONAL CHAT ACHIEVEMENTS ===
  {
    slug: 'first-words',
    name: 'First Words',
    title: 'First Words',
    description: 'Send your first chat message',
    category: 'chat',
    rarity: 'common',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 406,
  },
  {
    slug: 'chatterbox',
    name: 'Chatterbox',
    title: 'Chatterbox',
    description: 'Send 100 messages in a single day',
    category: 'chat',
    rarity: 'uncommon',
    targetValue: 100,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 407,
  },
  {
    slug: 'ghost-of-chat',
    name: 'Ghost of Chat',
    title: 'Ghost of Chat',
    description: 'Go 30 days without sending a message',
    category: 'chat',
    rarity: 'uncommon',
    targetValue: 30,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 408,
  },
  {
    slug: 'debate-champion',
    name: 'Debate Champion',
    title: 'Debate Champion',
    description: 'Participate in a heated discussion with 20+ back-and-forth messages',
    category: 'chat',
    rarity: 'uncommon',
    targetValue: 20,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 409,
  },
  {
    slug: 'emoji-master',
    name: 'Emoji Master',
    title: 'Emoji Master',
    description: 'Use 50+ different emojis in your messages',
    category: 'chat',
    rarity: 'uncommon',
    targetValue: 50,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 410,
  },

  // === ADDITIONAL PARTICIPATION ACHIEVEMENTS ===
  {
    slug: 'daily-visitor',
    name: 'Daily Visitor',
    title: 'Daily Visitor',
    description: 'Log in every day for 7 consecutive days',
    category: 'participation',
    rarity: 'common',
    targetValue: 7,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 506,
  },
  {
    slug: 'weekly-regular',
    name: 'Weekly Regular',
    title: 'Weekly Regular',
    description: 'Log in every day for 30 consecutive days',
    category: 'participation',
    rarity: 'uncommon',
    targetValue: 30,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 507,
  },
  {
    slug: 'profile-perfectionist',
    name: 'Profile Perfectionist',
    title: 'Profile Perfectionist',
    description: 'Complete your profile with bio, location, and avatar',
    category: 'participation',
    rarity: 'common',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 508,
  },
  {
    slug: 'social-butterfly',
    name: 'Social Butterfly',
    title: 'Social Butterfly',
    description: 'Follow 25 other users',
    category: 'participation',
    rarity: 'uncommon',
    targetValue: 25,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 509,
  },
  {
    slug: 'influence-peddler',
    name: 'Influence Peddler',
    title: 'Influence Peddler',
    description: 'Have 100+ users follow you',
    category: 'participation',
    rarity: 'rare',
    targetValue: 100,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 510,
  },

  // === ADDITIONAL EVENT ACHIEVEMENTS ===
  {
    slug: 'spacex-oracle',
    name: 'SpaceX Oracle',
    title: 'SpaceX Oracle',
    description: 'Correctly predict 5 SpaceX launch outcomes',
    category: 'event',
    rarity: 'rare',
    targetValue: 5,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 604,
  },
  {
    slug: 'crypto-prophet',
    name: 'Crypto Prophet',
    title: 'Crypto Prophet',
    description: 'Correctly predict a major crypto price movement',
    category: 'event',
    rarity: 'rare',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 605,
  },
  {
    slug: 'twitter-sage',
    name: 'Twitter Sage',
    title: 'Twitter Sage',
    description: 'Predict 3 Twitter/X policy changes correctly',
    category: 'event',
    rarity: 'rare',
    targetValue: 3,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 606,
  },
  {
    slug: 'neuralink-visionary',
    name: 'Neuralink Visionary',
    title: 'Neuralink Visionary',
    description: 'Correctly predict a Neuralink milestone',
    category: 'event',
    rarity: 'legendary',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 607,
  },

  // === ADDITIONAL SECRET ACHIEVEMENTS ===
  {
    slug: 'meme-legend',
    name: 'Meme Legend',
    title: 'Meme Legend',
    description: 'Create content that becomes a community inside joke',
    category: 'secret',
    rarity: 'secret',
    targetValue: 1,
    autoAward: false,
    manualOnly: true,
    isShame: false,
    sortOrder: 705,
  },
  {
    slug: 'easter-egg-hunter',
    name: 'Easter Egg Hunter',
    title: 'Easter Egg Hunter',
    description: 'Discover a hidden feature in the platform',
    category: 'secret',
    rarity: 'secret',
    targetValue: 1,
    autoAward: false,
    manualOnly: true,
    isShame: false,
    sortOrder: 706,
  },
  {
    slug: 'dev-whisperer',
    name: 'Dev Whisperer',
    title: 'Dev Whisperer',
    description: 'Successfully suggest a feature that gets implemented',
    category: 'secret',
    rarity: 'secret',
    targetValue: 1,
    autoAward: false,
    manualOnly: true,
    isShame: false,
    sortOrder: 707,
  },

  // === PONG GAMING CATEGORY ===
  {
    slug: 'pong-first-blood',
    name: 'First Blood',
    title: 'First Blood',
    description: 'Win your first Pong match.',
    category: 'pong',
    rarity: 'common',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 401,
  },
  {
    slug: 'pong-10-wins',
    name: 'Table Regular',
    title: 'Table Regular',
    description: 'Win 10 Pong matches.',
    category: 'pong',
    rarity: 'common',
    targetValue: 10,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 402,
  },
  {
    slug: 'pong-50-wins',
    name: 'Spin Doctor',
    title: 'Spin Doctor',
    description: 'Win 50 Pong matches.',
    category: 'pong',
    rarity: 'rare',
    targetValue: 50,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 403,
  },
  {
    slug: 'pong-100-wins',
    name: 'Arcade Royalty',
    title: 'Arcade Royalty',
    description: 'Win 100 Pong matches.',
    category: 'pong',
    rarity: 'legendary',
    targetValue: 100,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 404,
  },
  {
    slug: 'pong-100-matches',
    name: 'Grinder',
    title: 'Grinder',
    description: 'Play 100 Pong matches.',
    category: 'pong',
    rarity: 'common',
    targetValue: 100,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 410,
  },
  {
    slug: 'pong-500-matches',
    name: 'Marathoner',
    title: 'Marathoner',
    description: 'Play 500 Pong matches.',
    category: 'pong',
    rarity: 'rare',
    targetValue: 500,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 411,
  },
  {
    slug: 'pong-1000-matches',
    name: 'Endless Rally',
    title: 'Endless Rally',
    description: 'Play 1000 Pong matches.',
    category: 'pong',
    rarity: 'legendary',
    targetValue: 1000,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 412,
  },
  {
    slug: 'pong-streak-3',
    name: 'Hot Hands I',
    title: 'Hot Hands I',
    description: 'Win 3 matches in a row.',
    category: 'pong',
    rarity: 'common',
    targetValue: 3,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 420,
  },
  {
    slug: 'pong-streak-5',
    name: 'Hot Hands II',
    title: 'Hot Hands II',
    description: 'Win 5 matches in a row.',
    category: 'pong',
    rarity: 'rare',
    targetValue: 5,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 421,
  },
  {
    slug: 'pong-streak-10',
    name: 'Inferno',
    title: 'Inferno',
    description: 'Win 10 matches in a row.',
    category: 'pong',
    rarity: 'legendary',
    targetValue: 10,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 422,
  },
  {
    slug: 'pong-streak-20',
    name: 'Unstoppable',
    title: 'Unstoppable',
    description: 'Win 20 matches in a row.',
    category: 'pong',
    rarity: 'legendary',
    targetValue: 20,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 423,
  },
  {
    slug: 'pong-perfect-11-0',
    name: 'Perfect Game',
    title: 'Perfect Game',
    description: 'Win 11–0.',
    category: 'pong',
    rarity: 'legendary',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 430,
  },
  {
    slug: 'pong-comeback-king',
    name: 'Pong Comeback King',
    title: 'Pong Comeback King',
    description: 'Win after trailing by 5+ points.',
    category: 'pong',
    rarity: 'legendary',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 431,
  },
  {
    slug: 'pong-wall-builder',
    name: 'Wall Builder',
    title: 'Wall Builder',
    description: 'Hold opponent to ≤2 points.',
    category: 'pong',
    rarity: 'rare',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 432,
  },
  {
    slug: 'pong-speedrunner',
    name: 'Speedrunner',
    title: 'Speedrunner',
    description: 'Win a match in under 60 seconds.',
    category: 'pong',
    rarity: 'rare',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 433,
  },
  {
    slug: 'pong-ai-easy',
    name: 'Bot Breaker: Easy',
    title: 'Bot Breaker: Easy',
    description: 'Beat Easy AI.',
    category: 'pong',
    rarity: 'common',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 440,
  },
  {
    slug: 'pong-ai-medium',
    name: 'Bot Breaker: Medium',
    title: 'Bot Breaker: Medium',
    description: 'Beat Medium AI.',
    category: 'pong',
    rarity: 'common',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 441,
  },
  {
    slug: 'pong-ai-hard',
    name: 'Bot Breaker: Hard',
    title: 'Bot Breaker: Hard',
    description: 'Beat Hard AI.',
    category: 'pong',
    rarity: 'rare',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 442,
  },
  {
    slug: 'pong-ai-impossible',
    name: 'Bot Breaker: Impossible',
    title: 'Bot Breaker: Impossible',
    description: 'Beat Impossible AI.',
    category: 'pong',
    rarity: 'legendary',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 443,
  },
  {
    slug: 'pong-highroller-1k',
    name: 'Pong High Stakes I',
    title: 'Pong High Stakes I',
    description: 'Win with a wager ≥ 1,000.',
    category: 'pong',
    rarity: 'common',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 450,
  },
  {
    slug: 'pong-highroller-10k',
    name: 'Pong High Stakes II',
    title: 'Pong High Stakes II',
    description: 'Win with a wager ≥ 10,000.',
    category: 'pong',
    rarity: 'rare',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 451,
  },
  {
    slug: 'pong-highroller-50k',
    name: 'Pong High Stakes III',
    title: 'Pong High Stakes III',
    description: 'Win with a wager ≥ 50,000.',
    category: 'pong',
    rarity: 'legendary',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 452,
  },
  {
    slug: 'pong-highroller-100k',
    name: 'Pong High Stakes IV',
    title: 'Pong High Stakes IV',
    description: 'Win with a wager ≥ 100,000.',
    category: 'pong',
    rarity: 'legendary',
    targetValue: 1,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 453,
  },
  {
    slug: 'pong-elo-1400',
    name: 'Gold Threshold',
    title: 'Gold Threshold',
    description: 'Reach Elo 1400.',
    category: 'pong',
    rarity: 'common',
    targetValue: 1400,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 460,
  },
  {
    slug: 'pong-elo-1800',
    name: 'Platinum Threshold',
    title: 'Platinum Threshold',
    description: 'Reach Elo 1800.',
    category: 'pong',
    rarity: 'rare',
    targetValue: 1800,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 461,
  },
  {
    slug: 'pong-elo-2200',
    name: 'Diamond Threshold',
    title: 'Diamond Threshold',
    description: 'Reach Elo 2200.',
    category: 'pong',
    rarity: 'legendary',
    targetValue: 2200,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 462,
  },
  {
    slug: 'pong-elo-2600',
    name: 'Master Threshold',
    title: 'Master Threshold',
    description: 'Reach Elo 2600.',
    category: 'pong',
    rarity: 'legendary',
    targetValue: 2600,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 463,
  },
  {
    slug: 'pong-elo-3000',
    name: 'Grandmaster',
    title: 'Grandmaster',
    description: 'Reach Elo 3000.',
    category: 'pong',
    rarity: 'legendary',
    targetValue: 3000,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 464,
  },
  {
    slug: 'pong-freeplay-enthusiast',
    name: 'Freeplay Enthusiast',
    title: 'Freeplay Enthusiast',
    description: 'Win 10 freeplay matches.',
    category: 'pong',
    rarity: 'common',
    targetValue: 10,
    autoAward: true,
    manualOnly: false,
    isShame: false,
    sortOrder: 470,
  },
  {
    slug: 'pong-ragequit-shame',
    name: 'Cable Pulled',
    title: 'Cable Pulled',
    description: 'Forfeit 3 matches by disconnect.',
    category: 'pong',
    rarity: 'shame',
    targetValue: 3,
    autoAward: true,
    manualOnly: false,
    isShame: true,
    sortOrder: 498,
  },
  {
    slug: 'pong-bot-loss-shame',
    name: 'Whiff Wizard',
    title: 'Whiff Wizard',
    description: 'Lose to Easy AI twice in a row.',
    category: 'pong',
    rarity: 'shame',
    targetValue: 2,
    autoAward: true,
    manualOnly: false,
    isShame: true,
    sortOrder: 499,
  },
];

export { SEED_ACHIEVEMENTS };
export type { AchievementSeed };