/**
 * Domain Layer - Moderation Types
 *
 * Content moderation, user bans, and admin actions
 */

// ============================================================================
// Moderation Queue Types
// ============================================================================

/**
 * Moderation Queue Entry
 */
export interface ModerationQueueEntry {
  id: number;
  contentId: number;
  contentType: ModerationContentType;
  status: ModerationStatus;
  priority: ModerationPriority;
  flags: ModerationFlag[];
  submittedBy?: number; // userId who flagged
  assignedTo?: number; // moderator userId
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Moderation Content Types
 */
export const ModerationContentType = {
  ARTICLE: 'article',
  PREDICTION: 'prediction',
  CONTENT: 'content', // Posts/comments
  MESSAGE: 'message', // Chat messages
  USER_PROFILE: 'user_profile',
} as const;

export type ModerationContentType =
  (typeof ModerationContentType)[keyof typeof ModerationContentType];

/**
 * Moderation Status
 */
export const ModerationStatus = {
  PENDING: 'pending',
  IN_REVIEW: 'in_review',
  APPROVED: 'approved',
  REJECTED: 'rejected',
  FLAGGED: 'flagged',
  ESCALATED: 'escalated',
} as const;

export type ModerationStatus =
  (typeof ModerationStatus)[keyof typeof ModerationStatus];

/**
 * Moderation Priority
 */
export const ModerationPriority = {
  LOW: 'low',
  NORMAL: 'normal',
  HIGH: 'high',
  URGENT: 'urgent',
} as const;

export type ModerationPriority =
  (typeof ModerationPriority)[keyof typeof ModerationPriority];

// ============================================================================
// Moderation Flags
// ============================================================================

/**
 * Moderation Flag
 */
export interface ModerationFlag {
  id: string;
  type: FlagType;
  reason: string;
  severity: FlagSeverity;
  flaggedBy: number; // userId
  flaggedAt: Date;
  autoGenerated: boolean;
}

/**
 * Flag Types
 */
export const FlagType = {
  SPAM: 'spam',
  HARASSMENT: 'harassment',
  HATE_SPEECH: 'hate_speech',
  VIOLENCE: 'violence',
  SEXUAL_CONTENT: 'sexual_content',
  MISINFORMATION: 'misinformation',
  COPYRIGHT: 'copyright',
  DUPLICATE: 'duplicate',
  LOW_QUALITY: 'low_quality',
  OTHER: 'other',
} as const;

export type FlagType = (typeof FlagType)[keyof typeof FlagType];

/**
 * Flag Severity
 */
export const FlagSeverity = {
  MINOR: 'minor',
  MODERATE: 'moderate',
  SEVERE: 'severe',
  CRITICAL: 'critical',
} as const;

export type FlagSeverity = (typeof FlagSeverity)[keyof typeof FlagSeverity];

// ============================================================================
// Moderation Actions
// ============================================================================

/**
 * Moderation Action
 */
export interface ModerationAction {
  id: string;
  queueEntryId: number;
  action: ModActionType;
  reason: string;
  moderatorId: number;
  targetUserId?: number;
  metadata?: Record<string, unknown>;
  createdAt: Date;
}

/**
 * Moderation Action Types
 */
export const ModActionType = {
  APPROVE: 'approve',
  REJECT: 'reject',
  DELETE: 'delete',
  HIDE: 'hide',
  EDIT: 'edit',
  WARN_USER: 'warn_user',
  MUTE_USER: 'mute_user',
  BAN_USER: 'ban_user',
  UNBAN_USER: 'unban_user',
  ESCALATE: 'escalate',
  RESOLVE: 'resolve',
} as const;

export type ModActionType = (typeof ModActionType)[keyof typeof ModActionType];

// ============================================================================
// User Bans and Restrictions
// ============================================================================

/**
 * User Ban
 */
export interface UserBan {
  id: number;
  userId: number;
  type: BanType;
  reason: string;
  bannedBy: number; // moderator userId
  startDate: Date;
  endDate?: Date; // null = permanent
  isActive: boolean;
  metadata?: {
    contentId?: number;
    previousBans?: number;
    appealable?: boolean;
  };
}

/**
 * Ban Types
 */
export const BanType = {
  TEMPORARY: 'temporary',
  PERMANENT: 'permanent',
  SHADOW: 'shadow', // User can post but content is hidden
  CHAT_ONLY: 'chat_only', // Can't chat but can use other features
  BETTING_RESTRICTED: 'betting_restricted', // Can't place bets
  FULL: 'full', // Complete platform ban
} as const;

export type BanType = (typeof BanType)[keyof typeof BanType];

/**
 * User Mute
 */
export interface UserMute {
  id: number;
  userId: number;
  scope: MuteScope;
  reason: string;
  mutedBy: number; // moderator userId
  startDate: Date;
  endDate?: Date; // null = permanent
  isActive: boolean;
}

/**
 * Mute Scopes
 */
export const MuteScope = {
  CHAT: 'chat',
  COMMENTS: 'comments',
  PREDICTIONS: 'predictions',
  ALL_CONTENT: 'all_content',
} as const;

export type MuteScope = (typeof MuteScope)[keyof typeof MuteScope];

/**
 * User Warning
 */
export interface UserWarning {
  id: number;
  userId: number;
  reason: string;
  severity: WarningSeverity;
  issuedBy: number; // moderator userId
  issuedAt: Date;
  acknowledged: boolean;
  acknowledgedAt?: Date;
}

/**
 * Warning Severity
 */
export const WarningSeverity = {
  MINOR: 'minor',
  MODERATE: 'moderate',
  SEVERE: 'severe',
  FINAL: 'final', // Last warning before ban
} as const;

export type WarningSeverity = (typeof WarningSeverity)[keyof typeof WarningSeverity];

// ============================================================================
// Moderation Reports
// ============================================================================

/**
 * Moderation Report
 */
export interface ModerationReport {
  id: string;
  period: {
    start: Date;
    end: Date;
  };
  stats: ModerationStats;
  actions: ModerationActionSummary[];
  topModerators: ModeratorPerformance[];
  generatedAt: Date;
}

/**
 * Moderation Statistics
 */
export interface ModerationStats {
  totalQueued: number;
  totalProcessed: number;
  approved: number;
  rejected: number;
  averageReviewTime: number; // milliseconds
  flagsReceived: number;
  autoFlags: number;
  userFlags: number;
  bansIssued: number;
  warningsIssued: number;
  mutesIssued: number;
}

/**
 * Moderation Action Summary
 */
export interface ModerationActionSummary {
  action: ModActionType;
  count: number;
  byContentType: Record<ModerationContentType, number>;
}

/**
 * Moderator Performance
 */
export interface ModeratorPerformance {
  moderatorId: number;
  moderatorName: string;
  actionsProcessed: number;
  averageReviewTime: number; // milliseconds
  accuracy?: number; // Percentage (if peer review enabled)
  specializations: ModerationContentType[];
}

// ============================================================================
// Auto-Moderation
// ============================================================================

/**
 * Auto-Moderation Rule
 */
export interface AutoModerationRule {
  id: string;
  name: string;
  description: string;
  enabled: boolean;
  contentType: ModerationContentType[];
  conditions: AutoModCondition[];
  action: AutoModAction;
  priority: number;
  createdBy: number;
  createdAt: Date;
}

/**
 * Auto-Moderation Condition
 */
export interface AutoModCondition {
  type: 'keyword' | 'regex' | 'length' | 'spam_score' | 'user_history';
  operator: 'contains' | 'matches' | 'equals' | 'greater_than' | 'less_than';
  value: string | number;
  caseSensitive?: boolean;
}

/**
 * Auto-Moderation Action
 */
export interface AutoModAction {
  type: 'flag' | 'auto_reject' | 'require_review' | 'shadow_hide';
  severity: FlagSeverity;
  notifyModerators: boolean;
  notifyUser?: boolean;
}

/**
 * Auto-Moderation Result
 */
export interface AutoModerationResult {
  triggered: boolean;
  rules: string[]; // Rule IDs that triggered
  action: AutoModAction;
  confidence: number; // 0-100
}
